import assert from "node:assert/strict";
import test from "node:test";
import type { Product } from "@affiliateos/shared";
import { MarketplaceProviderRegistry, MockMarketplaceProvider, MockSocialMediaProvider, ProductOpportunityService, SafeTemplateContentGenerator, SocialMediaProviderRegistry, matchAudiences } from "../src/domain/foundations.js";

const product: Product = { id: "00000000-0000-4000-8000-000000000010", marketplaceId: "00000000-0000-4000-8000-000000000011", externalProductId: "sku-1", name: "Skincare Deal", category: "skincare", priceCents: 10000, currency: "IDR", ratingMilli: 4750, reviewCount: 1000, soldCount: 5000, productUrl: "https://example.com/product", status: "active", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" };
test("provider registries resolve explicitly registered adapters", async () => { const marketplaces = new MarketplaceProviderRegistry(); marketplaces.register(new MockMarketplaceProvider([product])); assert.equal((await marketplaces.get("mock").searchProducts("skin")).length, 1); assert.throws(() => marketplaces.get("unknown")); const social = new SocialMediaProviderRegistry(); social.register(new MockSocialMediaProvider()); assert.equal((await social.get("mock").publish(await new SafeTemplateContentGenerator().generateSocialPost(product, "instagram"))).externalPostId, "mock-post"); });
test("opportunity scores use available signals and disclose uncertainty", () => { const result = new ProductOpportunityService().score(product, 1000, 1); assert.ok(result.score > 0); assert.match(result.disclaimer, /not a prediction/i); assert.deepEqual(matchAudiences(product), ["skincare", "beauty", "lifestyle", "deal-hunters"]); });
test("template content includes no unsupported product claims", async () => { const content = await new SafeTemplateContentGenerator().generateShortVideoScript(product, "tiktok"); assert.match(content.script ?? "", /listed product details/); assert.ok(!content.caption.includes("best")); });
