-- Additive migration: 0000 remains the sole owner of legacy tables. New tables use
-- IF NOT EXISTS so an existing, manually-provisioned database is not destroyed.
CREATE TABLE IF NOT EXISTS "marketplaces" ("id" uuid PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "slug" varchar(100) NOT NULL, "status" varchar(20) NOT NULL, "configuration" jsonb DEFAULT '{}'::jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "marketplaces_slug_unique" ON "marketplaces" ("slug");
CREATE TABLE IF NOT EXISTS "affiliate_accounts" ("id" uuid PRIMARY KEY NOT NULL, "marketplace_id" uuid NOT NULL REFERENCES "marketplaces"("id"), "name" varchar(200) NOT NULL, "external_reference" varchar(255), "status" varchar(20) NOT NULL, "credential_reference" varchar(255), "configuration" jsonb DEFAULT '{}'::jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "affiliate_accounts_marketplace_reference_unique" ON "affiliate_accounts" ("marketplace_id", "external_reference");
CREATE TABLE IF NOT EXISTS "products" ("id" uuid PRIMARY KEY NOT NULL, "marketplace_id" uuid NOT NULL REFERENCES "marketplaces"("id"), "external_product_id" varchar(255) NOT NULL, "name" varchar(500) NOT NULL, "description" varchar(10000), "category" varchar(255), "price_cents" bigint NOT NULL, "original_price_cents" bigint, "currency" varchar(3) NOT NULL, "rating_milli" integer, "review_count" integer DEFAULT 0 NOT NULL, "sold_count" integer DEFAULT 0 NOT NULL, "image_url" varchar(2048), "product_url" varchar(2048) NOT NULL, "status" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "products_marketplace_external_unique" ON "products" ("marketplace_id", "external_product_id"); CREATE INDEX IF NOT EXISTS "products_marketplace_status_idx" ON "products" ("marketplace_id", "status"); CREATE INDEX IF NOT EXISTS "products_category_idx" ON "products" ("category");
CREATE TABLE IF NOT EXISTS "affiliate_offers" ("id" uuid PRIMARY KEY NOT NULL, "product_id" uuid NOT NULL REFERENCES "products"("id"), "affiliate_account_id" uuid NOT NULL REFERENCES "affiliate_accounts"("id"), "external_offer_id" varchar(255), "commission_rate_bps" integer, "commission_amount_cents" bigint, "affiliate_url" varchar(2048) NOT NULL, "status" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "affiliate_offers_account_external_unique" ON "affiliate_offers" ("affiliate_account_id", "external_offer_id"); CREATE INDEX IF NOT EXISTS "affiliate_offers_product_status_idx" ON "affiliate_offers" ("product_id", "status");
CREATE TABLE IF NOT EXISTS "campaigns" ("id" uuid PRIMARY KEY NOT NULL, "name" varchar(200) NOT NULL, "objective" varchar(100) NOT NULL, "status" varchar(20) NOT NULL, "start_at" timestamp with time zone, "end_at" timestamp with time zone, "audience" jsonb DEFAULT '{}'::jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS "campaign_offers" ("campaign_id" uuid NOT NULL REFERENCES "campaigns"("id"), "affiliate_offer_id" uuid NOT NULL REFERENCES "affiliate_offers"("id"), "created_at" timestamp with time zone NOT NULL); CREATE UNIQUE INDEX IF NOT EXISTS "campaign_offers_unique" ON "campaign_offers" ("campaign_id", "affiliate_offer_id");
CREATE TABLE IF NOT EXISTS "tracking_links" ("id" uuid PRIMARY KEY NOT NULL, "affiliate_offer_id" uuid NOT NULL REFERENCES "affiliate_offers"("id"), "campaign_id" uuid REFERENCES "campaigns"("id"), "code" varchar(100) NOT NULL, "destination_url" varchar(2048) NOT NULL, "status" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL); CREATE UNIQUE INDEX IF NOT EXISTS "tracking_links_code_unique" ON "tracking_links" ("code");
CREATE TABLE IF NOT EXISTS "clicks" ("id" uuid PRIMARY KEY NOT NULL, "tracking_link_id" uuid NOT NULL REFERENCES "tracking_links"("id"), "occurred_at" timestamp with time zone NOT NULL, "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL); CREATE INDEX IF NOT EXISTS "clicks_link_occurred_idx" ON "clicks" ("tracking_link_id", "occurred_at");
CREATE TABLE IF NOT EXISTS "social_accounts" ("id" uuid PRIMARY KEY NOT NULL, "platform" varchar(50) NOT NULL, "account_reference" varchar(255) NOT NULL, "status" varchar(20) NOT NULL, "connection" jsonb DEFAULT '{}'::jsonb NOT NULL, "credential_reference" varchar(255), "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL); CREATE UNIQUE INDEX IF NOT EXISTS "social_accounts_platform_reference_unique" ON "social_accounts" ("platform", "account_reference");
CREATE TABLE IF NOT EXISTS "content" ("id" uuid PRIMARY KEY NOT NULL, "product_id" uuid REFERENCES "products"("id"), "campaign_id" uuid REFERENCES "campaigns"("id"), "platform" varchar(50) NOT NULL, "content_type" varchar(50) NOT NULL, "title" varchar(500), "caption" varchar(5000), "script" varchar(10000), "cta" varchar(500), "status" varchar(20) NOT NULL, "scheduled_at" timestamp with time zone, "published_at" timestamp with time zone, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE INDEX IF NOT EXISTS "content_campaign_status_idx" ON "content" ("campaign_id", "status"); CREATE INDEX IF NOT EXISTS "content_scheduled_idx" ON "content" ("scheduled_at");
CREATE INDEX IF NOT EXISTS "conversions_affiliate_occurred_idx" ON "conversions" ("affiliate_id", "occurred_at"); CREATE INDEX IF NOT EXISTS "conversions_offer_occurred_idx" ON "conversions" ("offer_id", "occurred_at"); CREATE UNIQUE INDEX IF NOT EXISTS "commissions_conversion_unique" ON "commissions" ("conversion_id"); CREATE INDEX IF NOT EXISTS "commissions_affiliate_status_idx" ON "commissions" ("affiliate_id", "status");
