import type { FastifyInstance } from "fastify";
import type { Affiliate, Commission, Conversion, CreateAffiliateRequest, CreateConversionRequest, CreateOfferRequest, ListResponse, Offer, Product, ProductOpportunity } from "@affiliateos/shared";
import type { Services } from "../domain/container.js";
import { createAffiliateSchema, createConversionSchema, createOfferSchema, scoreProductSchema, marketplaceLinkSchema, marketplaceProductParamsSchema, marketplaceSearchSchema, marketplaceSlugSchema, createMarketplaceConnectionSchema, marketplaceEnableSchema, updateMarketplaceConnectionSchema, createCampaignSchema, updateCampaignSchema, campaignIdSchema, campaignOfferParamsSchema, createTrackingLinkSchema, trackingLinkIdSchema, recordClickSchema } from "./validation.js";
import { ProductOpportunityService } from "../domain/foundations.js";
const list=<T>(data:T[]):ListResponse<T>=>({data});
export function registerResourceRoutes(app:FastifyInstance,services:Services):void{
 app.get("/api/v1/affiliates",async()=>list(await services.affiliates.list())); app.post<{Body:CreateAffiliateRequest}>("/api/v1/affiliates",async(r,p)=>p.status(201).send(await services.affiliates.create(createAffiliateSchema.parse(r.body))));
 app.get("/api/v1/offers",async()=>list(await services.offers.list())); app.post<{Body:CreateOfferRequest}>("/api/v1/offers",async(r,p)=>p.status(201).send(await services.offers.create(createOfferSchema.parse(r.body))));
 app.get("/api/v1/conversions",async()=>list(await services.conversions.list())); app.post<{Body:CreateConversionRequest}>("/api/v1/conversions",async(r,p)=>p.status(201).send(await services.conversions.create(createConversionSchema.parse(r.body)))); app.get("/api/v1/commissions",async()=>list(await services.commissions.list()));
 app.post<{Body:{product:Product;commissionRateBps?:number;audienceRelevance?:number}}>("/api/v1/product-opportunities/score",async(r)=>{const i=scoreProductSchema.parse(r.body);return new ProductOpportunityService().score(i.product,i.commissionRateBps,i.audienceRelevance);});
 app.get("/api/v1/marketplaces/providers",async()=>list(await services.marketplace.listProviders())); app.get("/api/v1/marketplaces",async()=>list(await services.marketplace.listConnections())); app.post("/api/v1/marketplaces",async(r,p)=>p.status(201).send(await services.marketplace.createConnection(createMarketplaceConnectionSchema.parse(r.body)))); app.get("/api/v1/marketplaces/:connectionSlug",async r=>services.marketplace.getConnection(marketplaceSlugSchema.parse(r.params).connectionSlug)); app.patch("/api/v1/marketplaces/:connectionSlug",async r=>services.marketplace.updateConnection(marketplaceSlugSchema.parse(r.params).connectionSlug,updateMarketplaceConnectionSchema.parse(r.body))); app.put("/api/v1/marketplaces/:connectionSlug/enabled",async r=>services.marketplace.setEnabled(marketplaceSlugSchema.parse(r.params).connectionSlug,marketplaceEnableSchema.parse(r.body).enabled)); app.post("/api/v1/marketplaces/:connectionSlug/test",async r=>services.marketplace.testConnection(marketplaceSlugSchema.parse(r.params).connectionSlug)); app.get("/api/v1/marketplaces/:connectionSlug/health",async r=>{const c=await services.marketplace.getConnection(marketplaceSlugSchema.parse(r.params).connectionSlug);return {status:c.healthStatus,error:c.healthError,metadata:c.healthMetadata,lastCheckedAt:c.lastCheckedAt,lastSuccessfulCheckAt:c.lastSuccessfulCheckAt,lastSuccessfulSyncAt:c.lastSuccessfulSyncAt};});
 app.post("/api/v1/marketplaces/:connectionSlug/products/discover",async r=>list(await services.marketplace.discoverProducts(marketplaceSlugSchema.parse(r.params).connectionSlug))); app.get("/api/v1/marketplaces/:connectionSlug/products/search",async r=>{const i=marketplaceSearchSchema.parse({...r.params as object,...r.query as object});return list(await services.marketplace.searchProducts(i.connectionSlug,i.query));}); app.get("/api/v1/marketplaces/:connectionSlug/products/:externalProductId",async r=>{const i=marketplaceProductParamsSchema.parse(r.params);return services.marketplace.getProduct(i.connectionSlug,i.externalProductId);}); app.get("/api/v1/marketplaces/:connectionSlug/products/:externalProductId/offers",async r=>{const i=marketplaceProductParamsSchema.parse(r.params);return list(await services.marketplace.getOffers(i.connectionSlug,i.externalProductId));}); app.post("/api/v1/marketplaces/:connectionSlug/products/:externalProductId/offers/:externalOfferId/affiliate-link",async r=>{const i=marketplaceLinkSchema.parse(r.params);return services.marketplace.generateAffiliateLink(i.connectionSlug,i.externalProductId,i.externalOfferId);});
 app.get("/api/v1/campaigns",async()=>list(await services.campaigns.list())); app.post("/api/v1/campaigns",async(r,p)=>p.status(201).send(await services.campaigns.create(createCampaignSchema.parse(r.body)))); app.get("/api/v1/campaigns/:campaignId",async r=>services.campaigns.get(campaignIdSchema.parse(r.params).campaignId)); app.patch("/api/v1/campaigns/:campaignId",async r=>services.campaigns.update(campaignIdSchema.parse(r.params).campaignId,updateCampaignSchema.parse(r.body))); app.get("/api/v1/campaigns/:campaignId/offers",async r=>list(await services.campaigns.listOffers(campaignIdSchema.parse(r.params).campaignId))); app.post("/api/v1/campaigns/:campaignId/offers/:affiliateOfferId",async r=>services.campaigns.attachOffer(campaignOfferParamsSchema.parse(r.params).campaignId,campaignOfferParamsSchema.parse(r.params).affiliateOfferId)); app.delete("/api/v1/campaigns/:campaignId/offers/:affiliateOfferId",async r=>{const i=campaignOfferParamsSchema.parse(r.params);await services.campaigns.removeOffer(i.campaignId,i.affiliateOfferId);return {status:"removed"};});
 app.get("/api/v1/tracking-links",async r=>{const q=r.query as {campaignId?:string};return list(await services.tracking.list(q.campaignId));}); app.post("/api/v1/tracking-links",async(r,p)=>p.status(201).send(await services.tracking.create(createTrackingLinkSchema.parse(r.body)))); app.get("/api/v1/tracking-links/:trackingLinkId",async r=>services.tracking.get(trackingLinkIdSchema.parse(r.params).trackingLinkId)); app.post("/api/v1/tracking-links/:trackingLinkId/clicks",async r=>services.tracking.recordClick(trackingLinkIdSchema.parse(r.params).trackingLinkId,recordClickSchema.parse(r.body))); app.get("/api/v1/tracking-links/:trackingLinkId/stats",async r=>services.tracking.stats(trackingLinkIdSchema.parse(r.params).trackingLinkId));
}
