import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { DomainError } from "../domain/errors.js";
import { requireOperator } from "./auth.js";
import { createAffiliateSchema, createConversionSchema, createOfferSchema, createCampaignSchema, createContentSchema, updateCampaignSchema, updateContentSchema, createSocialAccountSchema, marketplaceEnableSchema, createMarketplaceConnectionSchema, updateMarketplaceConnectionSchema, marketplaceSlugSchema, marketplaceSearchSchema, marketplaceProductParamsSchema, marketplaceLinkSchema, oauthStartSchema, oauthCallbackSchema, attributionSchema, analyticsCampaignParamsSchema, campaignIdQuerySchema, trackingLinkQuerySchema } from "./validation.js";
import type { Services } from "../domain/container.js";

const list = <T>(items: T[]) => items;

export function registerResourceRoutes(app: FastifyInstance, services: Services) {
  app.post("/api/v1/affiliates", async (request, reply) => reply.status(201).send(await services.affiliates.create(createAffiliateSchema.parse(request.body))));
  app.get("/api/v1/affiliates", async () => list(await services.affiliates.list()));
  app.post("/api/v1/offers", async (request, reply) => reply.status(201).send(await services.offers.create(createOfferSchema.parse(request.body))));
  app.get("/api/v1/offers", async () => list(await services.offers.list()));
  app.post("/api/v1/conversions", async (request, reply) => reply.status(201).send(await services.conversions.create(createConversionSchema.parse(request.body))));
  app.get("/api/v1/conversions", async () => list(await services.conversions.list()));
  app.post("/api/v1/conversions/:conversionId/attribution", async (request, reply) => reply.status(201).send(await services.attribution.create(attributionSchema.parse({ ...(request.params as object), ...(request.body as object) }))));
  app.get("/api/v1/conversions/:conversionId/attribution", async (request) => services.attribution.get((request.params as { conversionId: string }).conversionId));
  app.get("/api/v1/commissions", async () => list(await services.commissions.list()));
  app.get("/api/v1/analytics/campaigns/:campaignId", async (request) => services.analytics.campaign((request.params as { campaignId: string }).campaignId));
  app.get("/api/v1/marketplaces", async () => list(await services.marketplace.listConnections()));
  app.get("/api/v1/products", async () => list(await services.marketplace.listProducts()));
  app.get("/api/v1/affiliate-offers", async () => list(await services.marketplace.listAffiliateOffers()));
  app.post("/api/v1/marketplaces", async (request, reply) => { const connection = await services.marketplace.createConnection(createMarketplaceConnectionSchema.parse(request.body)); request.log.info({ event: "marketplace_connection_created", connectionSlug: connection.slug, providerSlug: connection.providerSlug }); return reply.status(201).send(connection); });
  app.get("/api/v1/marketplaces/:connectionSlug", async (request) => services.marketplace.getConnection(marketplaceSlugSchema.parse(request.params).connectionSlug));
  app.patch("/api/v1/marketplaces/:connectionSlug", async (request) => { const connection = await services.marketplace.updateConnection(marketplaceSlugSchema.parse(request.params).connectionSlug, updateMarketplaceConnectionSchema.parse(request.body)); request.log.info({ event: "marketplace_connection_updated", connectionSlug: connection.slug, providerSlug: connection.providerSlug }); return connection; });
  app.put("/api/v1/marketplaces/:connectionSlug/enabled", { preHandler: requireOperator }, async (request, reply) => { const input = marketplaceEnableSchema.parse(request.body); const connection = await services.marketplace.setEnabled(marketplaceSlugSchema.parse(request.params).connectionSlug, input.enabled, "confirmation" in input ? input.confirmation : undefined); request.log.info({ event: "marketplace_connection_enabled_changed", connectionSlug: connection.slug, enabled: connection.enabled, operatorId: request.auth!.operatorId }); return connection; });
  app.post("/api/v1/marketplaces/:connectionSlug/test", async (request) => { const connection = await services.marketplace.testConnection(marketplaceSlugSchema.parse(request.params).connectionSlug); request.log.info({ event: "marketplace_connection_tested", connectionSlug: connection.slug, healthStatus: connection.healthStatus }); return connection; });
  app.get("/api/v1/marketplaces/:connectionSlug/health", async (request) => { const connection = await services.marketplace.getConnection(marketplaceSlugSchema.parse(request.params).connectionSlug); return { status: connection.healthStatus, error: connection.healthStatus === "unhealthy" ? "Marketplace connection is unhealthy." : undefined, lastCheckedAt: connection.lastCheckedAt, lastSuccessfulCheckAt: connection.lastSuccessfulCheckAt, lastSuccessfulSyncAt: connection.lastSuccessfulSyncAt }; });
  app.post("/api/v1/marketplaces/:connectionSlug/products/discover", async (request) => { const { connectionSlug } = marketplaceSlugSchema.parse(request.params); return list(await services.marketplace.discoverProducts(connectionSlug)); });
  app.get("/api/v1/marketplaces/:connectionSlug/products/search", async (request) => { const { connectionSlug, query } = await Promise.resolve(marketplaceSearchSchema.parse({ ...(request.params as object), ...(request.query as object) })); return list(await services.marketplace.searchProducts(connectionSlug, query)); });
  app.get("/api/v1/marketplaces/:connectionSlug/products/:externalProductId", async (request) => { const { connectionSlug, externalProductId } = marketplaceProductParamsSchema.parse(request.params); return services.marketplace.getProduct(connectionSlug, externalProductId); });
  app.get("/api/v1/marketplaces/:connectionSlug/products/:externalProductId/offers", async (request) => { const { connectionSlug, externalProductId } = marketplaceProductParamsSchema.parse(request.params); return list(await services.marketplace.getOffers(connectionSlug, externalProductId)); });
  app.post("/api/v1/marketplaces/:connectionSlug/products/:externalProductId/offers/:externalOfferId/affiliate-link", async (request) => { const input = marketplaceLinkSchema.parse(request.params); return services.marketplace.generateAffiliateLink(input.connectionSlug, input.externalProductId, input.externalOfferId); });
  app.get("/api/v1/campaigns", async () => list(await services.campaigns.list()));
  app.post("/api/v1/campaigns", async (request, reply) => reply.status(201).send(await services.campaigns.create(createCampaignSchema.parse(request.body))));
  app.get("/api/v1/campaigns/:campaignId", async (request) => services.campaigns.get((request.params as { campaignId: string }).campaignId));
  app.get("/api/v1/campaigns/:campaignId/offers", async (request) => list(await services.campaigns.listOffers((request.params as { campaignId: string }).campaignId)));
  app.post("/api/v1/campaigns/:campaignId/offers", async (request, reply) => reply.status(201).send(await services.campaigns.attachOffer((request.params as { campaignId: string }).campaignId, (request.body as { affiliateOfferId: string }).affiliateOfferId)));
  app.patch("/api/v1/campaigns/:campaignId", async (request) => services.campaigns.update((request.params as { campaignId: string }).campaignId, updateCampaignSchema.parse(request.body)));
  app.get("/api/v1/tracking-links", async (request) => list(await services.tracking.list(trackingLinkQuerySchema.parse(request.query))));
  app.post("/api/v1/tracking-links", async (request, reply) => reply.status(201).send(await services.tracking.create((request.body as { campaignId: string; affiliateOfferId: string; destinationUrl: string })))) ;
  app.post("/api/v1/clicks", async (request, reply) => reply.status(201).send(await services.tracking.recordClick(request.body as { trackingLinkId: string; idempotencyKey: string; occurredAt?: string })));
  app.get("/api/v1/tracking-links/:trackingLinkId/stats", async (request) => services.tracking.stats((request.params as { trackingLinkId: string }).trackingLinkId));
  app.post("/api/v1/content", async (request, reply) => reply.status(201).send(await services.content.create(createContentSchema.parse(request.body))));
  app.get("/api/v1/content", async (request) => list(await services.content.list((request.query as { campaignId?: string }).campaignId)));
  app.get("/api/v1/content/:contentId", async (request) => services.content.get((request.params as { contentId: string }).contentId));
  app.patch("/api/v1/content/:contentId", async (request) => services.content.update((request.params as { contentId: string }).contentId, updateContentSchema.parse(request.body)));
  app.post("/api/v1/social-accounts", async (request, reply) => reply.status(201).send(await services.socialAccounts.create(createSocialAccountSchema.parse(request.body))));
  app.get("/api/v1/social-accounts", async () => list(await services.socialAccounts.list()));
  app.get("/api/v1/oauth/:platform/start", async (request) => services.oauth.start(oauthStartSchema.parse({ ...(request.params as object), ...(request.query as object) })));
  app.get("/api/v1/oauth/:platform/callback", async (request) => services.oauth.callback(oauthCallbackSchema.parse({ ...(request.params as object), ...(request.query as object) })));
}
