import { randomUUID } from "node:crypto";
import { and, eq, inArray, sql } from "drizzle-orm";
import { autonomousExplorationStateEvents, autonomousExplorationStates } from "./schema.js";
import type { AutonomousDecisionAudit } from "../domain/autonomous-decision-audit.js";
import type { AutonomousExplorationDimension, AutonomousExplorationState, AutonomousExplorationStateRepository } from "../domain/autonomous-exploration-state.js";
type DatabaseExecutor=any;
const normalize=(value:string)=>value.trim().toLowerCase();
const dimensionsFor=(audit:AutonomousDecisionAudit):Array<{dimension:AutonomousExplorationDimension;key:string}>=>[
 {dimension:"marketplace",key:audit.marketplaceId},
 ...(audit.category?.trim()?[{dimension:"category" as const,key:normalize(audit.category)}]:[]),
 ...(audit.audienceSegments??[]).filter(v=>String(v).trim()).map(v=>({dimension:"audience" as const,key:normalize(String(v))}))
];
export class DrizzleAutonomousExplorationStateRepository implements AutonomousExplorationStateRepository{
 constructor(private readonly db:DatabaseExecutor){}
 async applyEvaluatedAudits(audits:AutonomousDecisionAudit[]){const evaluated=audits.filter(a=>a.selected&&a.selectionMode==="exploration"&&(a.outcome?.explorationEvaluation?.status==="promote-to-exploitation"||a.outcome?.explorationEvaluation?.status==="deprioritize"));if(!evaluated.length)return;await this.db.transaction(async(tx:DatabaseExecutor)=>{for(const audit of evaluated){const status=audit.outcome!.explorationEvaluation!.status;for(const {dimension,key} of dimensionsFor(audit)){await tx.insert(autonomousExplorationStates).values({id:randomUUID(),marketplaceId:audit.marketplaceId,dimension,dimensionKey:key,observedAt:audit.createdAt,createdAt:audit.createdAt,updatedAt:audit.createdAt}).onConflictDoNothing({target:[autonomousExplorationStates.marketplaceId,autonomousExplorationStates.dimension,autonomousExplorationStates.dimensionKey]});const [state]=await tx.select({id:autonomousExplorationStates.id}).from(autonomousExplorationStates).where(and(eq(autonomousExplorationStates.marketplaceId,audit.marketplaceId),eq(autonomousExplorationStates.dimension,dimension),eq(autonomousExplorationStates.dimensionKey,key))).limit(1);if(!state)continue;const inserted=await tx.insert(autonomousExplorationStateEvents).values({id:randomUUID(),stateId:state.id,auditId:audit.auditId,status,createdAt:audit.createdAt}).onConflictDoNothing({target:[autonomousExplorationStateEvents.stateId,autonomousExplorationStateEvents.auditId]}).returning({id:autonomousExplorationStateEvents.id});if(!inserted.length)continue;await tx.update(autonomousExplorationStates).set({sampleCount:sql`${autonomousExplorationStates.sampleCount}+1`,promotedCount:status==="promote-to-exploitation"?sql`${autonomousExplorationStates.promotedCount}+1`:autonomousExplorationStates.promotedCount,deprioritizedCount:status==="deprioritize"?sql`${autonomousExplorationStates.deprioritizedCount}+1`:autonomousExplorationStates.deprioritizedCount,observedAt:audit.createdAt,updatedAt:audit.createdAt}).where(eq(autonomousExplorationStates.id,state.id));}}});}
 async listByMarketplaces(marketplaceIds:string[]):Promise<AutonomousExplorationState[]>{if(!marketplaceIds.length)return[];const rows=await this.db.select().from(autonomousExplorationStates).where(inArray(autonomousExplorationStates.marketplaceId,marketplaceIds));return rows.map((r:any)=>({id:r.id,marketplaceId:r.marketplaceId,dimension:r.dimension as AutonomousExplorationDimension,dimensionKey:r.dimensionKey,sampleCount:r.sampleCount,promotedCount:r.promotedCount,deprioritizedCount:r.deprioritizedCount,observedAt:r.observedAt}));}
}