import { randomUUID } from "node:crypto";
import type { AffiliateAccount, AffiliateOffer, CreateMarketplaceConnectionRequest, MarketplaceConnection, MarketplaceConnectionView, MarketplaceProviderInfo, MarketplaceProductInput, Product, UpdateMarketplaceConnectionRequest } from "@affiliateos/shared";
import { DomainError } from "./errors.js";
import { MARKETPLACE_ENABLE_CONFIRMATION } from "./marketplace-confirmation.js";
import type { AffiliateAccountRepository, AffiliateOfferRepository, MarketplaceConnectionRepository, ProductCatalogRepository } from "./repository.js";
import { MarketplaceProviderRegistry } from "./foundations.js";
import type { ProviderEventSignatureHeaders } from "./foundations.js";
const now = () => new Date().toISOString();
const isUniqueViolation = (error: unknown): boolean => error instanceof Error && "code" in error && (error as { code?: unknown }).code === "23505";
export class MarketplaceService {
  constructor(private readonly registry: MarketplaceProviderRegistry, private readonly connections: MarketplaceConnectionRepository, private readonly products: ProductCatalogRepository, private readonly accounts: AffiliateAccountRepository, private readonly offers: AffiliateOfferRepository) {}
  async listProviders(): Promise<MarketplaceProviderInfo[]> { const configured = await this.connections.list(); return this.registry.list().map((provider) => ({ slug: provider.slug, displayName: provider.displayName, connectionMode: provider.connectionMode, configured: configured.some((connection) => connection.providerSlug === provider.slug), capabilities: [...provider.capabilities], supportsConnectionTest: Boolean(provider.testConnection) })); }
  async listConnections(): Promise<MarketplaceConnectionView[]> { return (await this.connections.list()).map(this.toView); }
  async listProducts(): Promise<Product[]> { return this.products.list(); }
  async listAffiliateOffers(): Promise<AffiliateOffer[]> { return this.offers.list(); }
  async getConnection(slug: string): Promise<MarketplaceConnectionView> { return this.toView(await this.connectionFor(slug)); }
  async verifyProviderEvent(slug: string, rawBody: string, headers: ProviderEventSignatureHeaders) { const connection = await this.connectionFor(slug); if (!connection.enabled || connection.status !== "active") throw new DomainError("MARKETPLACE_NOT_ACTIVE", "The marketplace connection is not enabled and active for event ingestion.", 409); const provider = this.getProvider(connection.providerSlug); if (!provider.verifyEventSignature) throw new DomainError("MARKETPLACE_WEBHOOK_UNSUPPORTED", "This marketplace provider does not support signed event ingestion.", 409); return provider.verifyEventSignature({ rawBody, headers, credentialReference: connection.credentialReference, configuration: connection.configuration }); }
  async getAffiliateAccount(slug: string): Promise<AffiliateAccount> { return this.accountFor(await this.connectionFor(slug)); }
  async createConnection(input: CreateMarketplaceConnectionRequest): Promise<MarketplaceConnectionView> { if (input.enabled) throw new DomainError("MARKETPLACE_CONFIRMATION_REQUIRED", "Marketplace connections must be created inactive and explicitly confirmed before activation.", 409); if (await this.connections.findBySlug(input.slug)) throw new DomainError("MARKETPLACE_CONNECTION_EXISTS", "A marketplace connection already uses this slug.", 409); const provider = this.getProvider(input.providerSlug); this.validate(provider, input.configuration ?? {}, input.credentialReference); const timestamp = now(); const connection: MarketplaceConnection = { id: randomUUID(), name: input.name, slug: input.slug, providerSlug: provider.slug, connectionMode: provider.connectionMode, status: "pending", enabled: false, credentialReference: input.credentialReference, configuration: input.configuration ?? {}, healthStatus: provider.testConnection ? "unverified" : "unsupported", healthError: undefined, healthMetadata: {}, createdAt: timestamp, updatedAt: timestamp }; try { return this.toView(await this.connections.save(connection)); } catch (error) { if (isUniqueViolation(error)) throw new DomainError("MARKETPLACE_CONNECTION_EXISTS", "A marketplace connection already uses this slug.", 409); throw error; } }
  async updateConnection(slug: string, input: UpdateMarketplaceConnectionRequest): Promise<MarketplaceConnectionView> { const connection = await this.connectionFor(slug); const provider = this.getProvider(connection.providerSlug); const configuration = input.configuration ?? connection.configuration; const credentialReference = input.credentialReference ?? connection.credentialReference; this.validate(provider, configuration, credentialReference); return this.toView(await this.connections.save({ ...connection, name: input.name ?? connection.name, configuration, credentialReference, healthStatus: provider.testConnection ? "unverified" : "unsupported", healthError: undefined, healthMetadata: {}, lastCheckedAt: undefined, lastSuccessfulCheckAt: undefined, updatedAt: now() })); }
  async setEnabled(slug: string, enabled: boolean, confirmation?: string): Promise<MarketplaceConnectionView> { if (enabled && confirmation !== MARKETPLACE_ENABLE_CONFIRMATION) throw new DomainError("MARKETPLACE_CONFIRMATION_REQUIRED", "Explicit user confirmation is required before activating a marketplace connection.", 409); const connection = await this.connectionFor(slug); const status: MarketplaceConnection["status"] = enabled ? (connection.healthStatus === "healthy" || connection.connectionMode === "mock" ? "active" : "pending") : "inactive"; return this.toView(await this.connections.save({ ...connection, enabled, status, updatedAt: now() })); }
  async testConnection(slug: string): Promise<MarketplaceConnectionView> { const connection = await this.connectionFor(slug); const provider = this.getProvider(connection.providerSlug); const checkedAt = now(); if (!provider.testConnection) throw new DomainError("MARKETPLACE_TEST_UNSUPPORTED", "This marketplace provider does not support connection testing.", 409); try { const result = await provider.testConnection({ credentialReference: connection.credentialReference, configuration: connection.configuration }); const status: MarketplaceConnection["status"] = connection.enabled ? "active" : "inactive"; return this.toView(await this.connections.save({ ...connection, status, healthStatus: "healthy", healthError: undefined, healthMetadata: result.metadata ?? {}, lastCheckedAt: checkedAt, lastSuccessfulCheckAt: checkedAt, updatedAt: checkedAt })); } catch (error) { const message = safeErrorMessage(error); return this.toView(await this.connections.save({ ...connection, status: "error", healthStatus: "unhealthy", healthError: message, healthMetadata: {}, lastCheckedAt: checkedAt, updatedAt: checkedAt })); } }
  async discoverProducts(connectionSlug: string): Promise<Product[]> { const { connection, provider } = await this.providerFor(connectionSlug); const inputs = await this.requireCapability<() => Promise<MarketplaceProductInput[]>>(provider, "discoverProducts")(); return Promise.all(inputs.map((input) => this.persistProduct(connection, input))); }
  async searchProducts(connectionSlug: string, query: string): Promise<Product[]> { const normalizedQuery = query.trim(); if (!normalizedQuery) throw new DomainError("INVALID_MARKETPLACE_QUERY", "Marketplace product search requires a non-empty query.", 400); const { connection, provider } = await this.providerFor(connectionSlug); return Promise.all((await this.requireCapability<(query: string) => Promise<MarketplaceProductInput[]>>(provider, "searchProducts")(normalizedQuery)).map((input) => this.persistProduct(connection, input))); }
  async getProduct(connectionSlug: string, externalProductId: string): Promise<Product> { const normalizedProductId = externalProductId.trim(); if (!normalizedProductId) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "Marketplace product lookup requires an external product id.", 400); const { connection, provider } = await this.providerFor(connectionSlug); const input = await this.requireCapability<(id: string) => Promise<MarketplaceProductInput | undefined>>(provider, "getProduct")(normalizedProductId); if (!input) throw new DomainError("PRODUCT_NOT_FOUND", "The marketplace product does not exist.", 404); return this.persistProduct(connection, input); }
  async getOffers(connectionSlug: string, externalProductId: string): Promise<AffiliateOffer[]> { const normalizedProductId = externalProductId.trim(); if (!normalizedProductId) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "Marketplace offer lookup requires an external product id.", 400); const { connection, provider } = await this.providerFor(connectionSlug); const product = await this.getProduct(connectionSlug, normalizedProductId); const account = await this.accountFor(connection); return Promise.all((await this.requireCapability<(id: string) => Promise<import("@affiliateos/shared").MarketplaceOfferInput[]>>(provider, "getOffers")(normalizedProductId)).map(async (input) => { validateMarketplaceOfferInput(input); const externalOfferId = input.externalOfferId.trim(); const existing = await this.offers.findByAccountOffer(account.id, externalOfferId); const timestamp = now(); const offer: AffiliateOffer = { id: existing?.id ?? randomUUID(), productId: product.id, affiliateAccountId: account.id, externalOfferId, priceCents: input.priceCents, currency: input.currency?.trim().toUpperCase(), commissionRateBps: input.commissionRateBps, commissionAmountCents: input.commissionAmountCents, availability: input.availability, availabilityMetadata: input.metadata ?? {}, affiliateUrl: existing?.affiliateUrl, affiliateLinkExpiresAt: input.affiliateLinkExpiresAt, affiliateLinkStatus: existing?.affiliateLinkStatus ?? "not_generated", status: input.availability === "out_of_stock" ? "inactive" : "active", createdAt: existing?.createdAt ?? timestamp, updatedAt: timestamp }; try { return await this.offers.save(offer); } catch (error) { if (!existing && isUniqueViolation(error)) { const raced = await this.offers.findByAccountOffer(account.id, externalOfferId); if (raced) return this.offers.save({ ...raced, productId: product.id, externalOfferId, priceCents: input.priceCents, currency: input.currency?.trim().toUpperCase(), commissionRateBps: input.commissionRateBps, commissionAmountCents: input.commissionAmountCents, availability: input.availability, availabilityMetadata: input.metadata ?? {}, affiliateLinkExpiresAt: input.affiliateLinkExpiresAt, status: input.availability === "out_of_stock" ? "inactive" : "active", updatedAt: timestamp }); } throw error; } })); }
function validateMarketplaceOfferInput(input: MarketplaceOfferInput): void {
  if (!input.externalOfferId.trim()) throw new DomainError("INVALID_MARKETPLACE_OFFER", "Marketplace offers require an external offer id.", 400);
  for (const [label, value] of [["price", input.priceCents], ["commission amount", input.commissionAmountCents]] as const) {
    if (value !== undefined && (!Number.isInteger(value) || value < 0)) throw new DomainError("INVALID_MARKETPLACE_OFFER", `Marketplace ${label} must be a non-negative integer.`, 400);
  }
  if (input.commissionRateBps !== undefined && (!Number.isInteger(input.commissionRateBps) || input.commissionRateBps < 0 || input.commissionRateBps > 10000)) throw new DomainError("INVALID_MARKETPLACE_OFFER", "Marketplace commission rate must be between 0 and 10000 basis points.", 400);
  if (input.commissionAmountCents !== undefined && input.priceCents !== undefined && input.commissionAmountCents > input.priceCents) throw new DomainError("INVALID_MARKETPLACE_OFFER", "Marketplace commission amount cannot exceed offer price.", 400);
  if (input.currency !== undefined && !/^[A-Za-z]{3}$/.test(input.currency.trim())) throw new DomainError("INVALID_MARKETPLACE_OFFER", "Marketplace offer currency must be a three-letter code.", 400);
  if (!["in_stock", "out_of_stock", "limited", "unknown"].includes(input.availability)) throw new DomainError("INVALID_MARKETPLACE_OFFER", "Marketplace offer availability is invalid.", 400);
  if (input.affiliateLinkExpiresAt !== undefined && !Number.isFinite(Date.parse(input.affiliateLinkExpiresAt))) throw new DomainError("INVALID_MARKETPLACE_OFFER", "Marketplace affiliate link expiry must be a valid timestamp.", 400);
}

  async generateAffiliateLink(connectionSlug: string, externalProductId: string, externalOfferId: string): Promise<AffiliateOffer> { const normalizedOfferId = externalOfferId.trim(); if (!normalizedOfferId) throw new DomainError("INVALID_MARKETPLACE_OFFER", "Affiliate link generation requires an external offer id.", 400); const { provider } = await this.providerFor(connectionSlug); const offers = await this.getOffers(connectionSlug, externalProductId); const offer = offers.find((item) => item.externalOfferId === normalizedOfferId);
    if (!offer) throw new DomainError("MARKETPLACE_OFFER_NOT_FOUND", "The marketplace offer does not exist for this product.", 404);
    if (offer.status !== "active" || offer.availability === "out_of_stock") throw new DomainError("MARKETPLACE_OFFER_NOT_ACTIVE", "Affiliate links can only be generated for active, available offers.", 409);
    const link = await this.requireCapability<(id: string) => Promise<{ url: string; expiresAt?: string }>>(provider, "generateAffiliateLink")(normalizedOfferId); validateAffiliateUrl(link.url); const expiresAt = link.expiresAt?.trim(); const expiry = expiresAt ? Date.parse(expiresAt) : undefined; const invalidExpiry = expiresAt !== undefined && !Number.isFinite(expiry); const expired = invalidExpiry || (expiry !== undefined && expiry <= Date.now()); return this.offers.save({ ...offer, affiliateUrl: link.url, affiliateLinkExpiresAt: invalidExpiry ? undefined : expiresAt, affiliateLinkStatus: expired ? "expired" : "active", updatedAt: now() }); }
  private async providerFor(connectionSlug: string) { const connection = await this.connections.findBySlug(connectionSlug); if (!connection) throw new DomainError("MARKETPLACE_NOT_CONFIGURED", "The marketplace connection is not configured.", 404); if (!connection.enabled || connection.status !== "active") throw new DomainError("MARKETPLACE_NOT_ACTIVE", "The marketplace connection is not enabled and verified.", 409); try { return { connection, provider: this.registry.get(connection.providerSlug) }; } catch { throw new DomainError("MARKETPLACE_PROVIDER_UNAVAILABLE", "The configured marketplace provider is unavailable.", 503); } }
  private async connectionFor(slug: string): Promise<MarketplaceConnection> { const connection = await this.connections.findBySlug(slug); if (!connection) throw new DomainError("MARKETPLACE_NOT_CONFIGURED", "The marketplace connection is not configured.", 404); return connection; }
  private getProvider(slug: string) { try { return this.registry.get(slug); } catch { throw new DomainError("MARKETPLACE_PROVIDER_UNAVAILABLE", "The requested marketplace provider is unavailable.", 404); } }
  private validate(provider: import("./foundations.js").MarketplaceProvider, configuration: Record<string, unknown>, credentialReference?: string): void { assertSafeConfiguration(configuration); if (credentialReference && !isOpaqueReference(credentialReference)) throw new DomainError("INVALID_CREDENTIAL_REFERENCE", "Credential references must be opaque secret-manager references.", 400); provider.validateConfiguration(configuration); }
  private requireCapability<T extends (...args: any[]) => any>(provider: import("./foundations.js").MarketplaceProvider, capability: keyof Pick<import("./foundations.js").MarketplaceProvider, "discoverProducts" | "searchProducts" | "getProduct" | "getOffers" | "generateAffiliateLink">): T { const method = provider[capability]; if (!method) throw new DomainError("MARKETPLACE_CAPABILITY_UNSUPPORTED", `This marketplace provider does not support ${capability}.`, 409); return method.bind(provider) as T; }
  private toView(connection: MarketplaceConnection): MarketplaceConnectionView { const { credentialReference: _secret, ...view } = connection; return { ...view, hasCredentialReference: Boolean(_secret) }; }
  private async persistProduct(connection: MarketplaceConnection, input: MarketplaceProductInput): Promise<Product> {
    validateMarketplaceProductInput(input);
    const externalProductId = input.externalProductId.trim();
    const existing = await this.products.findByMarketplaceProduct(connection.id, externalProductId);
    const timestamp = now();
    const product: Product = { id: existing?.id ?? randomUUID(), marketplaceId: connection.id, externalProductId, name: input.name.trim(), description: input.description?.trim(), category: input.category?.trim(), priceCents: input.priceCents, originalPriceCents: input.originalPriceCents, currency: input.currency.toUpperCase(), ratingMilli: input.ratingMilli, reviewCount: input.reviewCount ?? 0, soldCount: input.soldCount ?? 0, imageUrl: input.imageUrl, productUrl: input.productUrl, status: input.availability === "out_of_stock" ? "inactive" : "active", createdAt: existing?.createdAt ?? timestamp, updatedAt: timestamp }; try { return await this.products.save(product); } catch (error) { if (!existing && isUniqueViolation(error)) { const raced = await this.products.findByMarketplaceProduct(connection.id, input.externalProductId); if (raced) return this.products.save({ ...raced, name: input.name.trim(), description: input.description?.trim(), category: input.category?.trim(), priceCents: input.priceCents, originalPriceCents: input.originalPriceCents, currency: input.currency.trim().toUpperCase(), ratingMilli: input.ratingMilli, reviewCount: input.reviewCount ?? 0, soldCount: input.soldCount ?? 0, imageUrl: input.imageUrl, productUrl: input.productUrl, status: input.availability === "out_of_stock" ? "inactive" : "active", updatedAt: timestamp }); } throw error; } }
  private async accountFor(connection: MarketplaceConnection): Promise<AffiliateAccount> { const existing = await this.accounts.findByMarketplace(connection.id); if (existing) return existing; const timestamp = now(); const account: AffiliateAccount = { id: randomUUID(), marketplaceId: connection.id, name: `${connection.name} affiliate account`, status: "active", credentialReference: connection.credentialReference, configuration: {}, createdAt: timestamp, updatedAt: timestamp }; try { return await this.accounts.save(account); } catch (error) { if (isUniqueViolation(error)) { const raced = await this.accounts.findByMarketplace(connection.id); if (raced) return raced; } throw error; } }
}
const secretKey = /(secret|token|password|api[_-]?key|client[_-]?secret|authorization)/i;
function assertSafeConfiguration(value: Record<string, unknown>): void { for (const [key, item] of Object.entries(value)) { if (secretKey.test(key)) throw new DomainError("UNSAFE_PROVIDER_CONFIGURATION", "Provider configuration must not include credentials or secrets.", 400); if (item && typeof item === "object" && !Array.isArray(item)) assertSafeConfiguration(item as Record<string, unknown>); } }
function isOpaqueReference(value: string): boolean { return /^(?:[a-z][a-z0-9+.-]*:\/\/|[A-Z][A-Z0-9_]*:)[A-Za-z0-9._\-/]+$/i.test(value) && !/[\s]/.test(value); }
function safeErrorMessage(error: unknown): string { const message = error instanceof Error ? error.message : "Connection test failed."; return message.replace(/(token|secret|password|api[_-]?key|authorization)\s*[=:]\s*[^\s,;]+/gi, "$1=[REDACTED]").slice(0, 500); }

function validateAffiliateUrl(value: string): void {
  try {
    const url = new URL(value);
    if ((url.protocol !== "https:" && url.protocol !== "http:") || !url.hostname || url.username || url.password) throw new Error("unsupported or unsafe URL");
  } catch {
    throw new DomainError("INVALID_AFFILIATE_URL", "Generated affiliate links must use an HTTP or HTTPS URL.", 400);
  }
}


function validateMarketplaceProductInput(input: MarketplaceProductInput): void {
  if (!input.externalProductId.trim() || !input.name.trim()) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "Marketplace products require an external product id and name.", 400);
  if (!Number.isInteger(input.priceCents) || input.priceCents < 0) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "Marketplace product price must be a non-negative integer.", 400);
  if (input.originalPriceCents !== undefined && (!Number.isInteger(input.originalPriceCents) || input.originalPriceCents < 0)) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "Marketplace original price must be a non-negative integer.", 400);
  if (!/^[A-Za-z]{3}$/.test(input.currency.trim())) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "Marketplace product currency must be a three-letter code.", 400);
  if (!Number.isFinite(input.reviewCount ?? 0) || (input.reviewCount ?? 0) < 0 || !Number.isInteger(input.reviewCount ?? 0)) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "Marketplace review count must be a non-negative integer.", 400);
  if (!Number.isFinite(input.soldCount ?? 0) || (input.soldCount ?? 0) < 0 || !Number.isInteger(input.soldCount ?? 0)) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "Marketplace sold count must be a non-negative integer.", 400);
  if (input.ratingMilli !== undefined && (!Number.isInteger(input.ratingMilli) || input.ratingMilli < 0 || input.ratingMilli > 5000)) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "Marketplace rating must be between 0 and 5000 milli-points.", 400);
  if (!["in_stock", "out_of_stock", "limited", "unknown"].includes(input.availability)) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "Marketplace product availability is invalid.", 400);
  if (input.originalPriceCents !== undefined && input.originalPriceCents < input.priceCents) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "Marketplace original price cannot be below the current price.", 400);
  if (input.priceCents === 0 && input.originalPriceCents !== undefined && input.originalPriceCents > 0) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "A free marketplace product cannot have a positive original price.", 400);
  if (input.affiliateLinkExpiresAt !== undefined) {
    const expiry = Date.parse(input.affiliateLinkExpiresAt);
    if (!Number.isFinite(expiry)) throw new DomainError("INVALID_MARKETPLACE_PRODUCT", "Marketplace affiliate link expiry must be a valid timestamp.", 400);
  }
  validateMarketplaceUrl(input.productUrl, "product");
  if (input.imageUrl) validateMarketplaceUrl(input.imageUrl, "image");
}
function validateMarketplaceUrl(value: string, label: string): void {
  try {
    const url = new URL(value);
    if (url.protocol !== "https:" && url.protocol !== "http:") throw new Error("unsupported protocol");
  } catch {
    throw new DomainError("INVALID_MARKETPLACE_PRODUCT", `Marketplace ${label} URL must use HTTP or HTTPS.`, 400);
  }
}
