import type { MarketplaceOfferInput, MarketplaceProductInput } from "@affiliateos/shared";
import type { MarketplaceProvider } from "./foundations.js";
export interface ShopeeAffiliateClient { testConnection():Promise<Record<string,unknown>>; productOfferV2():Promise<MarketplaceProductInput[]>; searchProductOffers(query:string):Promise<MarketplaceProductInput[]>; getProduct(id:string):Promise<MarketplaceProductInput|undefined>; shopOfferV2():Promise<MarketplaceProductInput[]>; getOffers(id:string):Promise<MarketplaceOfferInput[]>; generateShortLink(id:string):Promise<{url:string;expiresAt?:string}>; conversionReport(since:string):Promise<{synced:number}>; }
export class ShopeeAffiliateProvider implements MarketplaceProvider {
 readonly slug="shopee-affiliate"; readonly displayName="Shopee Affiliate"; readonly connectionMode="official_api" as const; readonly capabilities=["discoverProducts","searchProducts","getProduct","getOffers","generateAffiliateLink","syncConversions"] as const;
 constructor(private readonly client:ShopeeAffiliateClient,private readonly configuration:{market:string;apiVersion:string}){}
 validateConfiguration(c:Record<string,unknown>):void{const market=c.market,version=c.apiVersion;if(typeof market!=="string"||!/^[A-Z]{2}$/.test(market))throw new Error("Shopee configuration requires a two-letter market code.");if(typeof version!=="string"||!/^v\d+$/.test(version))throw new Error("Shopee configuration requires an explicit Open API version.");}
 async testConnection():Promise<{metadata:Record<string,unknown>}>{return {metadata:{provider:this.slug,market:this.configuration.market,apiVersion:this.configuration.apiVersion,...await this.client.testConnection()}};}
 discoverProducts(){return this.client.productOfferV2();} searchProducts(q:string){return this.client.searchProductOffers(q);} getProduct(id:string){return this.client.getProduct(id);} getOffers(id:string){return this.client.getOffers(id);} generateAffiliateLink(id:string){return this.client.generateShortLink(id);} syncConversions(since:string){return this.client.conversionReport(since);}
}